@startuml

title __APPLIVISITEUR's Class Diagram__\n

  namespace  {
    namespace PY.appliVisiteur {
      class LPY.appliVisiteur.AppliVisiteurApplication {
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace CodeGen.Model {
        class LPY.appliVisiteur.CodeGen.Model.ApiCliModel {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Config {
        class LPY.appliVisiteur.Config.SwagerConfig {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Auth {
          class LPY.appliVisiteur.Controller.Auth.AuthController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        class LPY.appliVisiteur.Controller.BaseController {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Delegues {
          class LPY.appliVisiteur.Controller.Delegues.DelegueController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Delegues {
          class LPY.appliVisiteur.Controller.Delegues.DelegueDepartmentController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Delegues {
          class LPY.appliVisiteur.Controller.Delegues.DelegueDiplomaController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Delegues {
          class LPY.appliVisiteur.Controller.Delegues.DelegueDrugController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Delegues {
          class LPY.appliVisiteur.Controller.Delegues.DelegueDrugPresentation {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Delegues {
          class LPY.appliVisiteur.Controller.Delegues.DeleguePratitionnerController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Delegues {
          class LPY.appliVisiteur.Controller.Delegues.DelegueRegionController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Delegues {
          class LPY.appliVisiteur.Controller.Delegues.DelegueReportController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Delegues {
          class LPY.appliVisiteur.Controller.Delegues.DelegueSectorController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Delegues {
          class LPY.appliVisiteur.Controller.Delegues.DelegueWorkedTimeController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Visiteur {
          class LPY.appliVisiteur.Controller.Visiteur.VisitorDepartmentController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Visiteur {
          class LPY.appliVisiteur.Controller.Visiteur.VisitorDiplomaController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Visiteur {
          class LPY.appliVisiteur.Controller.Visiteur.VisitorDrugController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Visiteur {
          class LPY.appliVisiteur.Controller.Visiteur.VisitorDrugPresentationController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Visiteur {
          class LPY.appliVisiteur.Controller.Visiteur.VisitorPratitionnerController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Visiteur {
          class LPY.appliVisiteur.Controller.Visiteur.VisitorRegionController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Visiteur {
          class LPY.appliVisiteur.Controller.Visiteur.VisitorReportController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Visiteur {
          class LPY.appliVisiteur.Controller.Visiteur.VisitorSectorController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Visiteur {
          class LPY.appliVisiteur.Controller.Visiteur.VisitorUserController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Controller {
        namespace Visiteur {
          class LPY.appliVisiteur.Controller.Visiteur.VisitorWorkedTimeController {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Entity {
        class LPY.appliVisiteur.Model.Entity.Department {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Entity {
        class LPY.appliVisiteur.Model.Entity.Diploma {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Entity {
        class LPY.appliVisiteur.Model.Entity.Drug {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Entity {
        class LPY.appliVisiteur.Model.Entity.DrugPresentation {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Entity {
        class LPY.appliVisiteur.Model.Entity.Pratitionner {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Entity {
        class LPY.appliVisiteur.Model.Entity.Region {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Entity {
        class LPY.appliVisiteur.Model.Entity.Report {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Entity {
        class LPY.appliVisiteur.Model.Entity.Sector {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Entity {
        class LPY.appliVisiteur.Model.Entity.User {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Entity {
        class LPY.appliVisiteur.Model.Entity.WorkedTime {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Exception {
        class LPY.appliVisiteur.Model.Exception.AccessDeniedException {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Exception {
        class LPY.appliVisiteur.Model.Exception.RessouceNotFoundExeption {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Exception {
        class LPY.appliVisiteur.Model.Exception.UserNotFoundException {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.PrimaryKey {
        class LPY.appliVisiteur.Model.PrimaryKey.ReportPrimaryKey {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.PrimaryKey {
        class LPY.appliVisiteur.Model.PrimaryKey.WorkSchedulePrimaryKey {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.DepartmentRepository {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.DiplomaRepository {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.DrugPresentationRepository {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.DrugRepository {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.PraticionnerRepository {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.RegionRepository {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.ReportRepository {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.SecteurRepository {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.UserRepository {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.WorkedTimeRepository {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.RequestBody {
        class LPY.appliVisiteur.Model.RequestBody.Credential {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.RequestBody {
        namespace Visiteur {
          class LPY.appliVisiteur.Model.RequestBody.Visiteur.PresentationMedicamentBody {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.RequestBody {
        namespace Visiteur {
          class LPY.appliVisiteur.Model.RequestBody.Visiteur.RapportVisiteBody {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.RequestBody {
        namespace Visiteur {
          class LPY.appliVisiteur.Model.RequestBody.Visiteur.VisiteurBody {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.View.Visiteur {
        class LPY.appliVisiteur.Model.View.Visiteur.DepartmentView {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.View.Visiteur {
        class LPY.appliVisiteur.Model.View.Visiteur.DiplomaView {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.View.Visiteur {
        class LPY.appliVisiteur.Model.View.Visiteur.DrugPresentationView {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.View.Visiteur {
        class LPY.appliVisiteur.Model.View.Visiteur.DrugView {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.View.Visiteur {
        class LPY.appliVisiteur.Model.View.Visiteur.PratitionnerView {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.View.Visiteur {
        class LPY.appliVisiteur.Model.View.Visiteur.RegionView {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.View.Visiteur {
        class LPY.appliVisiteur.Model.View.Visiteur.ReportView {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.View.Visiteur {
        class LPY.appliVisiteur.Model.View.Visiteur.SectorView {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.View.Visiteur {
        class LPY.appliVisiteur.Model.View.Visiteur.UserView {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Model.View.Visiteur {
        class LPY.appliVisiteur.Model.View.Visiteur.WorkedTimeView {
        }
      }
    }
  }
  

  namespace  {
    namespace PY.appliVisiteur {
      namespace Service {
        class LPY.appliVisiteur.Service.Authentificator {
        }
      }
    }
  }
  

  namespace  {
    class MavenWrapperDownloader {
    }
  }
  

  LPY.appliVisiteur.Controller.Auth.AuthController -up-|> LPY.appliVisiteur.Controller.BaseController
  LPY.appliVisiteur.Controller.Auth.AuthController o-- LPY.appliVisiteur.Model.Repository.UserRepository : userRepository
  LPY.appliVisiteur.Controller.BaseController o-- LPY.appliVisiteur.Service.Authentificator : authentificator
  LPY.appliVisiteur.Controller.Delegues.DelegueController -up-|> LPY.appliVisiteur.Controller.Visiteur.VisitorUserController
  LPY.appliVisiteur.Controller.Delegues.DelegueDepartmentController -up-|> LPY.appliVisiteur.Controller.Visiteur.VisitorDepartmentController
  LPY.appliVisiteur.Controller.Delegues.DelegueDiplomaController -up-|> LPY.appliVisiteur.Controller.Visiteur.VisitorDiplomaController
  LPY.appliVisiteur.Controller.Delegues.DelegueDrugController -up-|> LPY.appliVisiteur.Controller.Visiteur.VisitorDrugController
  LPY.appliVisiteur.Controller.Delegues.DelegueDrugPresentation -up-|> LPY.appliVisiteur.Controller.Visiteur.VisitorDrugPresentationController
  LPY.appliVisiteur.Controller.Delegues.DeleguePratitionnerController -up-|> LPY.appliVisiteur.Controller.Visiteur.VisitorPratitionnerController
  LPY.appliVisiteur.Controller.Delegues.DelegueRegionController -up-|> LPY.appliVisiteur.Controller.Visiteur.VisitorRegionController
  LPY.appliVisiteur.Controller.Delegues.DelegueReportController -up-|> LPY.appliVisiteur.Controller.Visiteur.VisitorReportController
  LPY.appliVisiteur.Controller.Delegues.DelegueReportController o-- LPY.appliVisiteur.Model.Repository.UserRepository : userRepository
  LPY.appliVisiteur.Controller.Delegues.DelegueSectorController -up-|> LPY.appliVisiteur.Controller.Visiteur.VisitorSectorController
  LPY.appliVisiteur.Controller.Delegues.DelegueWorkedTimeController -up-|> LPY.appliVisiteur.Controller.Visiteur.VisitorWorkedTimeController
  LPY.appliVisiteur.Controller.Visiteur.VisitorDepartmentController -up-|> LPY.appliVisiteur.Controller.BaseController
  LPY.appliVisiteur.Controller.Visiteur.VisitorDepartmentController o-- LPY.appliVisiteur.Model.Repository.DepartmentRepository : departmentRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorDiplomaController -up-|> LPY.appliVisiteur.Controller.BaseController
  LPY.appliVisiteur.Controller.Visiteur.VisitorDiplomaController o-- LPY.appliVisiteur.Model.Repository.DiplomaRepository : diplomaRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorDrugController -up-|> LPY.appliVisiteur.Controller.BaseController
  LPY.appliVisiteur.Controller.Visiteur.VisitorDrugController o-- LPY.appliVisiteur.Model.Repository.DrugRepository : drugRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorDrugPresentationController -up-|> LPY.appliVisiteur.Controller.BaseController
  LPY.appliVisiteur.Controller.Visiteur.VisitorDrugPresentationController o-- LPY.appliVisiteur.Model.Repository.DrugPresentationRepository : drugPresentationRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorDrugPresentationController o-- LPY.appliVisiteur.Model.Repository.DrugRepository : drugRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorDrugPresentationController o-- LPY.appliVisiteur.Model.Repository.PraticionnerRepository : praticionnerRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorDrugPresentationController o-- LPY.appliVisiteur.Model.Repository.ReportRepository : reportRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorPratitionnerController -up-|> LPY.appliVisiteur.Controller.BaseController
  LPY.appliVisiteur.Controller.Visiteur.VisitorPratitionnerController o-- LPY.appliVisiteur.Model.Repository.PraticionnerRepository : praticionnerRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorRegionController -up-|> LPY.appliVisiteur.Controller.BaseController
  LPY.appliVisiteur.Controller.Visiteur.VisitorRegionController o-- LPY.appliVisiteur.Model.Repository.RegionRepository : regionRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorReportController -up-|> LPY.appliVisiteur.Controller.BaseController
  LPY.appliVisiteur.Controller.Visiteur.VisitorReportController o-- LPY.appliVisiteur.Model.Repository.DrugPresentationRepository : drugPresentationRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorReportController o-- LPY.appliVisiteur.Model.Repository.DrugRepository : drugRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorReportController o-- LPY.appliVisiteur.Model.Repository.PraticionnerRepository : praticionnerRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorReportController o-- LPY.appliVisiteur.Model.Repository.ReportRepository : reportRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorSectorController -up-|> LPY.appliVisiteur.Controller.BaseController
  LPY.appliVisiteur.Controller.Visiteur.VisitorSectorController o-- LPY.appliVisiteur.Model.Repository.SecteurRepository : secteurRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorUserController -up-|> LPY.appliVisiteur.Controller.BaseController
  LPY.appliVisiteur.Controller.Visiteur.VisitorUserController o-- LPY.appliVisiteur.Model.Repository.ReportRepository : reportRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorUserController o-- LPY.appliVisiteur.Model.Repository.UserRepository : userRepository
  LPY.appliVisiteur.Controller.Visiteur.VisitorWorkedTimeController -up-|> LPY.appliVisiteur.Controller.BaseController
  LPY.appliVisiteur.Controller.Visiteur.VisitorWorkedTimeController o-- LPY.appliVisiteur.Model.Repository.WorkedTimeRepository : workedTimeRepository
  LPY.appliVisiteur.Model.Entity.DrugPresentation o-- LPY.appliVisiteur.Model.Entity.Drug : drug
  LPY.appliVisiteur.Model.Entity.DrugPresentation o-- LPY.appliVisiteur.Model.Entity.Report : report
  LPY.appliVisiteur.Model.Entity.Region o-- LPY.appliVisiteur.Model.Entity.Sector : sector
  LPY.appliVisiteur.Model.Entity.Report o-- LPY.appliVisiteur.Model.Entity.Pratitionner : pratitionner
  LPY.appliVisiteur.Model.Entity.Report o-- LPY.appliVisiteur.Model.Entity.Region : region
  LPY.appliVisiteur.Model.Entity.Report o-- LPY.appliVisiteur.Model.Entity.User : user
  LPY.appliVisiteur.Model.Entity.User o-- LPY.appliVisiteur.Model.Entity.Region : region
  LPY.appliVisiteur.Model.Entity.WorkedTime o-- LPY.appliVisiteur.Model.Entity.Department : department
  LPY.appliVisiteur.Model.Entity.WorkedTime o-- LPY.appliVisiteur.Model.Entity.Region : region
  LPY.appliVisiteur.Model.Entity.WorkedTime o-- LPY.appliVisiteur.Model.Entity.User : user
  LPY.appliVisiteur.Model.PrimaryKey.ReportPrimaryKey .up.|> java.io.Serializable
  LPY.appliVisiteur.Model.PrimaryKey.WorkSchedulePrimaryKey .up.|> java.io.Serializable
  LPY.appliVisiteur.Model.PrimaryKey.WorkSchedulePrimaryKey o-- LPY.appliVisiteur.Model.Entity.User : user
  LPY.appliVisiteur.Service.Authentificator o-- LPY.appliVisiteur.Model.Repository.UserRepository : userRepository


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
