@startuml

title __REPOSITORY's Class Diagram__\n

    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.DepartmentRepository {
            {abstract} + findOneById()
        }
      }
    }

  

    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.DiplomaRepository {
            {abstract} + findOneById()
        }
      }
    }
  

    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.DrugPresentationRepository {
            {abstract} + findOneById()
        }
      }
    }

    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.DrugRepository {
            {abstract} + findOneById()
        }
      }
    }
  

    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.PraticionnerRepository {
            {abstract} + findOneById()
        }
      }
    }

    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.RegionRepository {
            {abstract} + findOneById()
        }
      }
    }
  

    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.ReportRepository {
            {abstract} + findById()
            {abstract} + findByUser()
            {abstract} + findByUserAndRegion()
            {abstract} + findOneByIdAndRegion()
            {abstract} + findOneByUserAndId()
        }
      }
    }
  

    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.SecteurRepository {
            {abstract} + findOneById()
        }
      }
    }
  

    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.UserRepository {
            {abstract} + findByLogin()
            {abstract} + findOneById()
        }
      }
    }
  

    namespace PY.appliVisiteur {
      namespace Model.Repository {
        interface LPY.appliVisiteur.Model.Repository.WorkedTimeRepository {
            {abstract} + findById()
            {abstract} + findByIdAndUser()
            {abstract} + findByUser()
        }
      }
    }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
