package LPY.appliVisiteur.Controller.auth;

import LPY.appliVisiteur.Model.Entity.User;
import LPY.appliVisiteur.Model.Repository.UserRepository;
import LPY.appliVisiteur.Model.RequestBody.Credential;
import com.auth0.jwt.JWT;
import com.auth0.jwt.algorithms.Algorithm;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.Map;


@RestController
public class AuthController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @RequestMapping(value = "/token", method = RequestMethod.POST)
    public String getVisiteur(@RequestBody Credential credential) {
        User user = userRepository.findByLogin(credential.getLogin());
        if(user != null)
        {
            Algorithm algorithm = Algorithm.HMAC256("secret");
            Map<String, Object> headerClaims = new HashMap();
            headerClaims.put("id", user.getId());
            String token = JWT.create()
                    .withIssuer("auth0")
                    .withHeader(headerClaims)
                    .sign(algorithm);
            return token;
        }

        return "mauvais login";
    }
}