package LPY.appliVisiteur.Controller;

import LPY.appliVisiteur.Model.Repository.VisiteurRepository;
import LPY.appliVisiteur.Model.Entity.Visiteur;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;


@RestController
public class VisiteurController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private VisiteurRepository visiteurRepository;

    @RequestMapping("/visiteur")
    public Iterable<Visiteur> getVisiteur() {
        return visiteurRepository.findAll();
    }
}