package LPY.appliVisiteur.Controller.Visiteur;

import LPY.appliVisiteur.Model.Entity.RapportVisite;
import LPY.appliVisiteur.Model.Repository.RapportVisiteRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;


@RestController
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private RapportVisiteRepository rapportVisiteRepository;

    @RequestMapping("/visiteur")
    public Iterable<RapportVisite> getVisiteur() {
        return rapportVisiteRepository.findAll();
    }
}