@startuml

title __VISITEUR's Class Diagram__\n

    namespace PY.appliVisiteur {
      namespace Model.RequestBody {
        namespace Visiteur {
          class LPY.appliVisiteur.Model.RequestBody.Visiteur.PresentationMedicamentBody {
              - IdMedicament : Long
              - IdRapportVisite : Long
              + getIdMedicament()
              + getIdRapportVisite()
              + setIdMedicament()
              + setIdRapportVisite()
          }
        }
      }
    }
  

    namespace PY.appliVisiteur {
      namespace Model.RequestBody {
        namespace Visiteur {
          class LPY.appliVisiteur.Model.RequestBody.Visiteur.RapportVisiteBody {
              - MedicamentId : Collection<Long>
              - note : String
              - praticienId : Long
              + getMedicamentId()
              + getNote()
              + getPraticienId()
              + setMedicamentId()
              + setNote()
              + setPraticienId()
          }
        }
      }
    }
  

    namespace PY.appliVisiteur {
      namespace Model.RequestBody {
        namespace Visiteur {
          class LPY.appliVisiteur.Model.RequestBody.Visiteur.VisiteurBody {
              - codePostal : String
              - nomVoie : String
              - numeroVoie : Integer
              - typeVoie : String
              - ville : String
              + getCodePostal()
              + getNomVoie()
              + getNumeroVoie()
              + getTypeVoie()
              + getVille()
              + setCodePostal()
              + setNomVoie()
              + setNumeroVoie()
              + setTypeVoie()
              + setVille()
          }
        }
      }
    }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
